### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by cschaf** [jchavarri/framer-boilerplate#2]
d:\Eigene_Dateien\Eigene_Dokumente\Programmierung\Websites\Prototypes\tourist-app>npm install
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN prefer global coffee-script@1.10.0 should be installed with -g

> tourist-app@1.0.0 postinstall d:\Eigene_Dateien\Eigene_Dokumente\Programmierung\Websites\Prototypes\tourist-app
> cd ./node_modules/framerjs && make

Der Befehl "make" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.  -> Windows dont know make?

npm WARN EPACKAGEJSON tourist-app@1.0.0 No description
npm WARN EPACKAGEJSON tourist-app@1.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\Shuffle\AppData\Roaming\nodejs\node.exe" "C:\Users\Shuffle\AppData\Roaming\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! tourist-app@1.0.0 postinstall: `cd ./node_modules/framerjs && make`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tourist-app@1.0.0 postinstall script 'cd ./node_modules/framerjs && make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tourist-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./node_modules/framerjs && make
npm ERR! You can get their info via:
npm ERR!     npm owner ls tourist-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\Eigene_Dateien\Eigene_Dokumente\Programmierung\Websites\Prototypes\tourist-app\npm-debug.log

**Comment by cschaf** [comment]
I installed http://gnuwin32.sourceforge.net/packages/make.htm and now it works a bit further.

Now I get this:

d:\Eigene_Dateien\Eigene_Dokumente\Programmierung\Websites\Prototypes\framer-boilerplate-master>npm
install
npm WARN install Couldn't install optional dependency: Unsupported

> framer-boilerplate@1.0.0 postinstall d:\Eigene_Dateien\Eigene_Dokumente\Programmierung\Websites\Prototypes\framer-boilerplatemaster
> cd ./node_modules/framerjs && make

npm install
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN EPEERINVALID mocha-phantomjs@3.6.0 requires a peer of phantomjs@1.9.1 - 1.9.7-15 but none w
as installed.
cd test/phantomjs; "d:/Eigene_Dateien/Eigene_Dokumente/Programmierung/Websites/Prototypes/framer-boi
lerplate-master/node_modules/framerjs/node_modules/.bin/bower" --config.analytics=false install
Der Dateiname oder die Erweiterung ist zu lang.
make: **\* [bootstrap] Fehler 1

npm WARN EPEERINVALID mocha-phantomjs@3.6.0 requires a peer of phantomjs@1.9.1 - 1.9.7-15 but none w
as installed.
npm WARN EPACKAGEJSON framer-boilerplate@1.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\Shuffle\AppData\Roaming\nodejs\node.exe" "C:\Users\Shuffle\AppData\
\Roaming\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! framer-boilerplate@1.0.0 postinstall: `cd ./node_modules/framerjs && make`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the framer-boilerplate@1.0.0 postinstall script 'cd ./node_modules/framerjs && ma
ke'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the framer-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./node_modules/framerjs && make
npm ERR! You can get their info via:
npm ERR!     npm owner ls framer-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\Eigene_Dateien\Eigene_Dokumente\Programmierung\Websites\Prototypes\framer-boilerplat
e-master\npm-debug.log

**Comment by jchavarri** [comment]
Hi @cschaf thanks for the report. I have just updated the project to remove the dependency with `make` so you will be able to install it without any issues on Windows. Could you try to call `npm install` with a fresh download of this latest version?

**Comment by cschaf** [comment]
I figuered all problems out. 1) changed framer package.json-> from 0.5 to version gulp-mocha-phantomjs: "^0.8.0". 2) Changed Makefile of framer from "cd test/phantomjs;"$(bin)/bower" --config.analytics=false install) to (cd test/phantomjs && "$(bin)/bower" --config.analytics=false install". 3) Used MinGw/bin/make.exe for building framer. 4) Biggest Promlem was that Windows only supports directory paths which length is smaller then 256 characters. 5) installed npm bower, coffe-script and gulp globally on my system. 6) Dowloaded and installed phantomjs.exe 

After all that i can run gulp and all works.

Your new version is great. Thank you!

**Comment by jchavarri** [comment]
Awesome! Let me know if you have any other ideas or ways to improve it. Closing! :)
