### ISSUE TITLE
Gulp export task

### ISSUE THREAD

**Issue by cschaf** [jchavarri/framer-boilerplate#3]
Hi its me again,
what can i do with the exported file from the gulp export. Is it possible to deploy to the framer server? I dont use framer studio.

Greetings
Christian

**Comment by jchavarri** [comment]
Hi Christian,

The `gulp export` command is useful if you want to share or open your project in Framer Studio. It just creates the folder and file structure required for Framer Studio to open it. 

Deploying to the official Framer server, as far as I know, is only possible from Framer Studio. If you want to deploy a project created with this boilerplate, I'm afraid you will need to do it manually.

**Comment by cschaf** [comment]
Maybe it is possible to push the source to the gh-pages branch on github.

**Comment by jchavarri** [comment]
Interesting! I will research a bit on how to handle git branches and commits from gulp. If you have any previous experience or other ideas on how you see this gh-pages export, please let me know.
