### ISSUE TITLE
FramerJS prebuilt not updated to latest version

### ISSUE THREAD

**Issue by elamotte** [jchavarri/framer-boilerplate#4]
As I said on FB, thanks for your work on this it's definitly need to be know better by the community!

As comment, the framerJS prebuilt version included (https://github.com/jchavarri/framerjs-prebuilt) do not point to the latest version of FramerJS http://builds.framerjs.com/.

As an example the function "onTap" is not included in the version actually included in your package.

**Comment by jchavarri** [comment]
Thanks for your contribution @elamotte 
I have [updated the framerjs-prebuilt](https://github.com/jchavarri/framerjs-prebuilt/commit/3b6500a345aba2ac6a142e1f1572e7d45edb31a7) repo to point to the latest commit in the master branch of Framer, so all the latest features should be available. You can get them rerunning the `npm install` command.

Closing the issue for now, please feel free to reopen if needed :)
